version: '3.9'
services:
 web:
  build: ./react_frontend
  container_name: react1
  ports:
   - "3000:3000"
  volumes:
   - ./react_frontend:/react-app
  stdin_open: true
  tty: true
 app:
  image: node:latest
  container_name: nodeapp
  environment:
   DB_HOST: mysql1
   DB_PORT: 3306
   DB_USER: root
   DB_PASSWORD: admin
  ports:
   - "8080:8080"
  command: ["bin/bash"]
  volumes:
   - ./Backend:/code
  depends_on:
   - mysql1 
  stdin_open: true
  tty: true
 mysql1:
  image: mysql:5.7
  platform: linux/x86_64 
  restart: always
  container_name: db1
  environment:
   - MYSQL_ROOT_PASSWORD=admin
  ports:
   - '3306:3306'
  volumes:
   - ./db:/var/lib/mysql
  stdin_open: true
  tty: true
volumes: 
  db:
     driver: local
    

# Citations:

# This Docker Compose configuration is adapted from the 'docker-compose.yml' file in the 'Fetch_Data' repository by Sandiecodes.
# GitHub Repository: https://github.com/Sandiecodes/Fetch_Data/blob/main/docker-compose.yml
# Accessed on: 10/18/2023

# This file is adapted from the repository by Sandiecodes.
# Accessed on: 11/01/2023
# https://github.com/Sandiecodes/React_Node_MySql/blob/main/docker-compose.yml


# This Docker Compose configuration was written with assistance from ChatGPT September 25 version 2023, and GitHub.copilot